### ISSUE TITLE
ERR_CONNECTION_RESET when import database on phpmyadmin

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#174] opened 2019-11-29 00:10 UTC
**Steps:**

1. Open cyberpanel database section
2. Select the domain
3. Open phpmyadmin
4. Select one database
5. Try to import (does not matter the size of database). It will give ERR_CONNECTION_RESET error whe it try to start upload. There is no error from google chrome inspect and nothing is logged in litespeed logs.

Probably this problem is relationated with (or same problem):
https://forums.cyberpanel.net/discussion/558/solved-trying-to-import-a-database-via-phpmyadmin-fails

I tried with firewall disabled and no results. Data center does not forcing any firewall or anti ddos. The connection is direct, I mean, no cloudflare or something like that.

- max_upload, max_execution and post size are increased
- selinux is in permissive mode

How can I debug this problem?

I am using Centos 7 updated with CyberPanel v1.9.

**Comment by istiak101** [comment] 2021-08-06 04:15
There could be many reasons for this, on your isp side/server side/due to bugs in server binary. As this is very older issue I think this can't be reproduced as of now. phpMyAdmin import works fine on my servers. I will close this after few days if I don't get any response from you.

**Closed as completed** 2021-08-06 05:45 UTC

**Comment by NobleZirwaHara** [comment] 2022-10-08 04:56
Did someone figure this out
