### ISSUE TITLE
Cyberpanel fail during upgrade

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/cyberpanel#298] opened 2020-04-03 01:15 UTC
I have one installation that I upgraded las weekend. Today I tried upgrade again and I am getting:

```bash
Collecting mysqlclient==1.4.6
  Using cached mysqlclient-1.4.6.tar.gz (85 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/CyberPanel/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-eq3pa9nr/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-eq3pa9nr/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-eq3pa9nr/mysqlclient/pip-egg-info
         cwd: /tmp/pip-install-eq3pa9nr/mysqlclient/
    Complete output (12 lines):
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-eq3pa9nr/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-eq3pa9nr/mysqlclient/setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-eq3pa9nr/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

command failed, exiting...
```

I am using Centos 7 with pip with last stable version.

**Comment by jordanlambrecht** [comment] 2021-02-06 07:17
@franciscopaniskaseker were you able to solve this? Additionally, you have over 10 open issues with this repo that are rounding the corner on a year old. Would you mind going through them all and closing out ones that are no longer relevant? This helps keep the Issues backlog clean.

**Comment by istiak101** [comment] 2021-05-31 11:57
Your installation didn't have libmaridb-dev package. I think this can be closed now as the issue is too old. @usmannasir @whattheserver @franciscopaniskaseker

**Closed as completed** 2021-05-31 11:58 UTC

**Comment by andremacola** [comment] 2021-12-02 02:18
On ubuntu 20.04 we cant upgrade to MariaDB 10.5 or 10.6
It breaks Cyberpanel instalation/upgrade proccess because it requires old mysqlclient and libmariadbclient-dev
