### ISSUE TITLE
Couldn't send/receive email after upgrading to version 2.1.1

### ISSUE THREAD

**Issue by h1dd3nsn1p3r** [litespeedtech/cyberpanel#585] opened 2021-04-16 08:18 UTC
@usmannasir 

Os: CentOs 7
Cloud provider: DO
Tested in: CP 2.1.1. Also tested in 2.0.3 by downgrading from 2.1.1

I know this BUG is already reported but I am adding this for reference. 

I noticed postfix was not running with the command `systemctl status postfix`. Then,

1. I installed postfix using the command `yum install postfix -y` & then started it using command `systemctl start postfix`
2. I also installed mailx  using command `yum install mailx -y`

If I do `echo "This is the body of the email" | mail -s "This is the subject line" myemail@mydomain.com` I got an email from the server. 

BUT, none of the emails sent from rainloop, POP, IMAP is working. Same case for receiving too. Is this something to do with MailScanner? 

Thanks,
Anuj

**Comment by master3395** [comment] 2021-04-16 09:02
Could have commented on my report also ;)
https://github.com/usmannasir/cyberpanel/issues/579

**Comment by paulshultz** [comment] 2021-04-16 14:44
Looks like the latest upgrade removes postfix.

Erased: 2:postfix3-mysql-3.5.8-1.gf.el7.x86_64
Erased: 2:postfix3-pcre-3.5.8-1.gf.el7.x86_64
Erased: 2:postfix3-ldap-3.5.8-1.gf.el7.x86_64
Erased: 2:postfix3-3.5.8-1.gf.el7.x86_64

I think the intent is to remove, and re-install but the install script does not re-install

**Comment by paulshultz** [comment] 2021-04-16 14:52
Looks like the ghettoforge.org mirror is out of the picture, so had to re-install manually.

wget http://mirror.ghettoforge.org/distributions/gf/el/7/plus/x86_64/postfix3-3.5.8-1.gf.el7.x86_64.rpm
wget http://mirror.ghettoforge.org/distributions/gf/el/7/plus/x86_64/postfix3-mysql-3.5.8-1.gf.el7.x86_64.rpm
wget http://mirror.ghettoforge.org/distributions/gf/el/7/plus/x86_64/postfix3-ldap-3.5.8-1.gf.el7.x86_64.rpm
wget http://mirror.ghettoforge.org/distributions/gf/el/7/plus/x86_64/postfix3-pcre-3.5.8-1.gf.el7.x86_64.rpm

rpm -Uvh postfix3-*.rpm
systemctl restart postfix

**Comment by franciscopaniskaseker** [comment] 2021-04-16 22:49
I did the manual installation as explained in https://github.com/usmannasir/cyberpanel/issues/585#issuecomment-821233083
Because the official tutorial https://cyberpanel.net/docs/email-not-working-after-cyberpanel-upgrade/ get a lot of package conflicts using yum. We are being note beta, but alpha testers here.

**Comment by meramsey** [comment] 2021-04-16 23:22
I think i found the cause of the issue and put out a fix
https://github.com/usmannasir/cyberpanel/commit/f865d0cb027bf2e325be46c882e6ffc9f37896f7

Let me know if it fixes the issue on centos where it failed to reinstall. 

Im testing the fix for Ubuntu currently but don't have a centos one setup to test on atm

**Comment by usmannasir** [comment] 2021-04-17 11:24
OK @whattheserver I've merged the commit to v2.1.1 and also published the debugging guide, so we can close this now.

**Closed as completed by usmannasir** 2021-04-17 11:24 UTC
