### ISSUE TITLE
[BUG] SSL NOT WORKING AFTER UPDATE 2.3

### ISSUE THREAD

**Issue by Gregory-Hepicloud** [litespeedtech/cyberpanel#911] opened 2022-07-01 09:01 UTC
**Describe the bug**
After update all ssl make SELF-SIGNED SSL all time
`"Max retries exceeded" with url: /.well-known/acme-challenge/ cyberpanel`

**To Reproduce**
Issue ssl or renew ssl make it SELF-SIGNED SSL

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/4592618/176861726-989893cf-c379-4e2a-81c2-edd76091f0f9.png)

**Operating system:**
AlmaLinux 8.6

**CyberPanel version:**
2.3

**Comment by usmannasir** [comment] 2022-07-01 18:17
Kindly show me your vhost config.

**Comment by Gregory-Hepicloud** [comment] 2022-07-06 16:33
we have try to reset cyberpanel and change os but we get all time this for all domain : 

Invalid response from http://mydomaine/.well-known/acme-challenge/TrZcm12KoiUzh3vfuj5Yh1DEeHzbzQMQqb70InCUsqg: 404

![image](https://user-images.githubusercontent.com/4592618/177599649-230526c3-8a98-4fa5-ae8c-6e1ac3faeb69.png)

Operating system: Ubuntu 20.04

CyberPanel version:
2.3

**Comment by Gregory-Hepicloud** [comment] 2022-07-06 17:01
we have make direct cert on website on zerossl and put to cyberpanel site working but ssl on panel or via cli not working like this bellow post

**Comment by usmannasir** [comment] 2022-07-07 05:34
If you have reset CP then it is not a bug. I will close this issue, please follow this guide: https://community.cyberpanel.net/t/how-to-fix-ssl-issues-in-cyberpanel/90

It could be DNS record issue, if you need any help, you can ask below that thread.

**Closed as completed by usmannasir** 2022-07-07 05:34 UTC

**Comment by Gregory-Hepicloud** [comment] 2022-07-07 07:38
Its not a dns issue its after update cyberpanel or install last update its stoped working with new install of cyberpanel same error 👍 

`[07.07.2022_07-32-25] Status Code: Unkown for: http://www.hepicloud.fr/.well-known/acme-challenge/hepicloud.fr. Error: HTTPConnectionPool(host='www.hepicloud.fr', port=80): Max retries exceeded with url: /.well-known/acme-challenge/hepicloud.fr (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf0fb14580>: Failed to establish a new connection: [Errno 111] Connection refused'))
[07.07.2022_07-32-25] Status Code: Unkown for: http://hepicloud.fr/.well-known/acme-challenge/hepicloud.fr. Error: HTTPConnectionPool(host='hepicloud.fr', port=80): Max retries exceeded with url: /.well-known/acme-challenge/hepicloud.fr (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fcf0fb849a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
[07.07.2022_07-32-41] /root/.acme.sh/acme.sh --issue -d hepicloud.fr -d www.hepicloud.fr --cert-file /etc/letsencrypt/live/hepicloud.fr/cert.pem --key-file /etc/letsencrypt/live/hepicloud.fr/privkey.pem --fullchain-file /etc/letsencrypt/live/hepicloud.fr/fullchain.pem -w /usr/local/lsws/Example/html -k ec-256 --force --server letsencrypt
[07.07.2022_07-32-41] Failed to obtain SSL for: hepicloud.fr and: www.hepicloud.fr
[07.07.2022_07-32-41] /root/.acme.sh/acme.sh --issue -d hepicloud.fr --cert-file /etc/letsencrypt/live/hepicloud.fr/cert.pem --key-file /etc/letsencrypt/live/hepicloud.fr/privkey.pem --fullchain-file /etc/letsencrypt/live/hepicloud.fr/fullchain.pem -w /usr/local/lsws/Example/html -k ec-256 --force --server letsencrypt
[07.07.2022_07-32-41] Failed to obtain SSL, issuing self-signed SSL for: hepicloud.fr
[07.07.2022_07-32-42] Connection unexpectedly closed
[07.07.2022_07-32-42] Self signed SSL issued for hepicloud.fr.`

if make ssl direct on officiel letsencrypte website its working but not if use cyberpanel with the error bellow

**Comment by Gregory-Hepicloud** [comment] 2022-07-07 07:46
and connection its working if try 👍 

`root@CyberPanelU:~# curl -v https://acme-v02.api.letsencrypt.org/directory
*   Trying 172.65.32.248:443...
* TCP_NODELAY set
* Connected to acme-v02.api.letsencrypt.org (172.65.32.248) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=acme-v02.api.letsencrypt.org
*  start date: Jul  2 19:06:17 2022 GMT
*  expire date: Sep 30 19:06:16 2022 GMT
*  subjectAltName: host "acme-v02.api.letsencrypt.org" matched cert's "acme-v02.api.letsencrypt.org"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x55780b2fa2f0)
> GET /directory HTTP/2
> Host: acme-v02.api.letsencrypt.org
> user-agent: curl/7.68.0
> accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< server: nginx
< date: Thu, 07 Jul 2022 07:43:35 GMT
< content-type: application/json
< content-length: 658
< cache-control: public, max-age=0, no-cache
< x-frame-options: DENY
< strict-transport-security: max-age=604800
< 
{
  "Wy4zC8UXLJA": "https://community.letsencrypt.org/t/adding-random-entries-to-the-directory/33417",
  "keyChange": "https://acme-v02.api.letsencrypt.org/acme/key-change",
  "meta": {
    "caaIdentities": [
      "letsencrypt.org"
    ],
    "termsOfService": "https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf",
    "website": "https://letsencrypt.org"
  },
  "newAccount": "https://acme-v02.api.letsencrypt.org/acme/new-acct",
  "newNonce": "https://acme-v02.api.letsencrypt.org/acme/new-nonce",
  "newOrder": "https://acme-v02.api.letsencrypt.org/acme/new-order",
  "revokeCert": "https://acme-v02.api.letsencrypt.org/acme/revoke-cert"
* Connection #0 to host acme-v02.api.letsencrypt.org left intact`

**Comment by mmabas77** [comment] 2022-12-27 22:30
Found any thing ? i have the same problem here
