### ISSUE TITLE
CentOS 8 - PowerDNS and PureFTPd errors (Version 1.9.2) and solutions

### ISSUE THREAD

**Issue by invipal** [litespeedtech/cyberpanel#191] opened 2019-12-28 23:34 UTC
1) PowerDNS config not writable, you need to change chmod. "chmod 666 /etc/pdns/pdns.conf"

2) UseFtpUsers variable trigger an error while starting PureFTPd (v1.0.49), you need remove it from "/etc/pure-ftpd/pure-ftpd.conf".

**Comment by usmannasir** [comment] 2019-12-30 10:18
Can you create a pull request?

**Comment by invipal** [comment] 2019-12-30 12:27
Sure, but firstly I need to find the version of PureFTPd which is added UseFtpUsers variable for fixed code. Because, UseFtpUsers variable is not wrong for latest versions of PureFTPd. There are so limited release notes on their site and their github repo.

**Comment by usmannasir** [comment] 2019-12-30 13:39
no problem, take your time @invipal

**Comment by themew** [comment] 2020-05-07 23:16
Does that mean it's possible to install Cyberpanel on CentOS 8 by choosing (No) on PureFTPd and PowerDNS? :)

**Comment by istiak101** [comment] 2020-05-08 00:58
@themew Yes. Since this is an old issue see if you can reproduce it installing with PowerDNS and PureFTPd. This might have been patched as current stable version is 2.0 . Please let us know your results so this issue can be closed.

**Comment by themew** [comment] 2020-05-08 02:17
Tried installing 2.0 with CentOS 8 updated to 8.1 with both PowerDNS and PureFTPd installed and it completed the install but the panel wouldn't start.  Tried starting it from the command line but still couldn't get it to start.  Only asking because we're moving to a new server and would prefer to install with C8.

**Comment by IOAyman** [comment] 2020-05-17 10:21
> Tried installing 2.0 with CentOS 8 updated to 8.1 with both PowerDNS and PureFTPd installed and it completed the install but the panel wouldn't start. Tried starting it from the command line but still couldn't get it to start.

I confirm too.

**Comment by jordanlambrecht** [comment] 2021-02-06 02:56
@invipal any updates on this?

**Comment by istiak101** [comment] 2021-08-07 01:58
As of 2.1.1 pdns.conf is 644 which is writable by owner and UseFtpUsers is commented out.

https://github.com/usmannasir/cyberpanel/blob/v2.1.1/install/pure-ftpd-one/pure-ftpd.conf#L21
https://github.com/usmannasir/cyberpanel/blob/v2.1.1/install/pure-ftpd/pure-ftpd.conf#L21
https://github.com/usmannasir/cyberpanel/blob/v2.1.1/install/install.py#L567-L575

As this is one of the oldest issue I will close this after few days assuming this no longer can be reproduced if I do not receive any new response.

**Closed as completed** 2021-08-10 09:56 UTC
