### ISSUE TITLE
[BUG] Attach git from child/subdomain

### ISSUE THREAD

**Issue by loukasstoltz** [litespeedtech/cyberpanel#887] opened 2022-05-31 16:44 UTC
**Describe the bug**
Unable to attach properly a git to sub-domain. 
When we would init Git they use a full domain path until a subdomain path to look the .SSH folder

**To Reproduce**
1 create a domain 
2 create a subdomain 
3 clic on manage git
4 clic on attach git 

**Screenshots**
File attached 

Path should be here  : /home/serveur.digital/public-html/laratest.serveur.digital
.ssh should be created here  
(or using the principal .ssh folder for the main name (/home/serveur.digital/.ssh/xxxx.pub ) 

**Operating system:**
Ubuntu 20.04 LTS

**CyberPanel version:**
2.3.1 : 01a9093bdbc2bbf14c9ab67133c248588dd8b225

![Capture d’écran 2022-05-31 à 18 38 40](https://user-images.githubusercontent.com/19878463/171228350-2e726244-e7ba-4728-af49-9b5e103137d8.png)

**Comment by usmannasir** [comment] 2022-06-07 10:20
![git-key](https://user-images.githubusercontent.com/17538454/172357043-6d7bfc84-99ae-431c-a52b-bed937bca396.png)

I've tried to reproduce via both cases, key shows up for me fine.

**Comment by loukasstoltz** [comment] 2022-06-07 12:18
Hi and thank you. 
I mean Subdomain, not principal domain name.
I have try it with an other domain  : 

• Check last CP version (done) 
• Delete domain 
• Recreate It 
• Create a subdomain like test.subdomain.com (with ssl ) in the path /home/subdomain.com/public_html/test.subdomain.com 
• Try again to initialise git, i got same error ... 

Would you like a vidéo?

**Comment by loukasstoltz** [comment] 2022-06-07 12:45
https://user-images.githubusercontent.com/19878463/172381584-a026523b-9a4c-4aee-9652-47742c56ca2a.mov

Here you can have a look

**Comment by usmannasir** [comment] 2022-06-07 13:23
Did the same like yours, still can't reproduce the error. What happens if you login via english lang and do the same?

**Comment by loukasstoltz** [comment] 2022-06-07 13:26
> Did the same like yours, still can't reproduce the error. What happens if you login via english lang and do the same?

As you can see i'm login in english, but i have installed french package to use ubuntu. (probably is why i get the message in french) 
Message you see meen : no file or folder found

**Comment by loukasstoltz** [comment] 2022-06-07 13:28
do you want access on it ?

**Comment by usmannasir** [comment] 2022-06-07 13:28
remove that french package and then try again.

**Comment by loukasstoltz** [comment] 2022-06-07 13:39
You have right! 
After that, i have now this awersome screen !
![Capture d’écran 2022-06-07 à 15 37 11](https://user-images.githubusercontent.com/19878463/172394438-0e317279-24aa-4343-a853-a9b955e9d464.png)


but Why it doesn't work for french users?  :-s

**Comment by usmannasir** [comment] 2022-06-07 13:40
Code depends on output from system and I think french output is different then the normal system output.

I will close this now.

**Closed as completed by usmannasir** 2022-06-07 13:40 UTC

**Comment by loukasstoltz** [comment] 2022-06-07 13:41
Ok, thank. you , should i update CP in english too ?
