### ISSUE TITLE
[BUG Cannot delete websites

### ISSUE THREAD

**Issue by zebrahosting** [litespeedtech/cyberpanel#1058] opened 2023-04-27 14:50 UTC
Cyberpanel v 2.3.5-dev
Ubu 22

Very simple: when trying to delete websites, i need to confirm, get the green bar that the site has been deleted but noting happens. Tried a few times with different sites and all fail.

This panel was originally installed with 2.3.2 and upgraded from there.
mail accounts where deleted first, sites set in suspended to see if that worked but no luck
Changed back to the original admin account (which the first step to disable in my system) but also the admin could not delete.

Main log:
[04.27.2023_14-36-11] (1146, "Table 'cyberpanel.websiteFunctions_backupsv2' doesn't exist") [Not able to remove virtual host configuration from main configuration file.]
[04.27.2023_14-36-37] (1008, "Can't drop database 'dkl5K8sKk0IdTy'; database doesn't exist")[deleteDatabase]

**Comment by atak946** [comment] 2023-05-01 10:31
@zebrahosting 

I'm having the same problem, I started having these problems after the upgrade.

I can't create ftp account, I can't delete a site, I started having a lot of trouble.

i don't know how to solve it.

**Comment by atak946** [comment] 2023-05-01 19:43
@zebrahosting i did review website functions code but i see they haven't changed anything.

in fact this action deleting web site files on the server but doesn't delete on mysql table (websiteFunctions_websites).

you can delete your web site in this table and you can check your files at /home/yourdomain.com.

actually that is their bug, they have to delete web site on the table for the solution.

you can check this solution for your issue.

**Comment by zebrahosting** [comment] 2023-05-01 23:39
Thanks for the check. Appreciate your feedback. I found that I can delete from the Wordpress list and there it disappears but not in the main website listing. It looks like there is more to it than only the table not being removed.
Currently on the road but I did a quick check and indeed the files in /home are deleted. 
In this case there were also certificate troubles and I see they are still there too. I would say deleting a website needs a real cleanup.

**Comment by umut-ore** [comment] 2023-05-02 19:37
I can confirm this issue is also in the 2.3.4 version commit 5aee24ae593cdbbf5b1ccea5ad3f9c8898d5a7b1
Folders related to the websites get deleted but the database entries are not being deleted due to foreign key constraints. Os is Ubuntu 20.04
I tried to delete them manually but got frustrated to be honest. 
I was wondering if the main entry points (domain) all foreign key had delete the related fields upon deletion would this still happen. Just a thought.

**Comment by EduVillas** [comment] 2023-05-04 00:08
Same issue with 2 VPS.

**Comment by shbs9** [comment] 2023-05-05 18:57
Let us reproduce this issue at ubuntu 22 and if some have on any other os let me know

**Comment by usmannasir** [comment] 2023-05-07 12:09
This issue is resolved with this commit, if you still face issue you can let us know: https://github.com/usmannasir/cyberpanel/commit/6eeaca15d3bb0defa1ef76bbaec642fb82230570

**Closed as completed by usmannasir** 2023-05-07 12:09 UTC
