### ISSUE TITLE
Issue with fresh installation

### ISSUE THREAD

**Issue by KewalT** [litespeedtech/cyberpanel#708] opened 2021-08-13 10:34 UTC
While installing to me Ubuntu service is throwing error under Running: root/.acme.sh/acme.sh --upgrade --auto-upgrade

Errno 2 No such file or directory: 'root/.acme.sh/acme.sh'
Oops, something went wrong..

**Comment by KewalT** [comment] 2021-08-13 11:14
![Capture](https://user-images.githubusercontent.com/52283926/129352308-9fccfd26-0c1c-41ea-ad65-428f05764d42.JPG)
Please help! I am stuck and has some critical dependencies..

**Comment by KewalT** [comment] 2021-08-13 12:01
Issue summary:

Resolving get.acme.sh (get.acme.sh)... 2606:4700:3032::6815:223e, 2606:4700:3031::ac43:c710, 104.21.34.62, . ..
Connecting to get.acme.sh (get.acme.sh)|2606:4700:3032::6815:223e|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘STDOUT’

                         [ <=>                                     ]     253  --.-KB/s    in 0s
2021-08-12 13:11:54 (9.13 MB/s) - written to stdout [253]

sh: line 1: syntax error near unexpected token <' sh: line 1: <style> body{margin:0px;padding:0px;}iframe{width:100%;height:100%}</style><iframe src="https://www.airtel.in/dot/" width="100%" height="100%" frameborder=0></iframe>'

[08.12.2021_13-11-54] #########################################################################

[08.12.2021_13-11-54] Running: /root/.acme.sh/acme.sh --upgrade --auto-upgrade

[08.12.2021_13-11-54] #########################################################################

Traceback (most recent call last):
File "install.py", line 2369, in
main()
File "install.py", line 2283, in main
checks.installAcme()
File "install.py", line 2101, in installAcme
preFlightsChecks.call(command, self.distro, command, command, 1, 0, os.EX_OSERR)
File "install.py", line 219, in call
res = subprocess.call(shlex.split(command))
File "/usr/lib64/python3.6/subprocess.py", line 287, in call
with Popen(*popenargs, **kwargs) as p:
File "/usr/lib64/python3.6/subprocess.py", line 729, in init
restore_signals, start_new_session)
File "/usr/lib64/python3.6/subprocess.py", line 1364, in _execute_child
raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/root/.acme.sh/acme.sh': '/root/.acme.sh/acme.sh'
Oops, something went wrong

**Comment by istiak101** [comment] 2021-08-13 19:03
Duplicate of #707.

**Closed as completed by istiak101** 2021-08-13 19:03 UTC
