### ISSUE TITLE
Rainloop admin password should be set to the same as the cyberpanel admin on install

### ISSUE THREAD

**Issue by master3395** [litespeedtech/cyberpanel#579] opened 2021-04-14 21:32 UTC
When updating from 2.0 V3
Rainloop admin login gets a random password that you have to manually find in
/usr/local/CyberCP/public

And copy the password, log in and then change the password.
Why not use the same password as the cp uses?

**Comment by meramsey** [comment] 2021-04-17 04:11
I love this idea. If you recall the exact file you found it in and can leave that noted here that would be helpful so we can see what all this change would require.

Update:It looks like the cause of this is in this location:
https://github.com/usmannasir/cyberpanel/blob/stable/install/install.py#L2322-L2350

**Comment by master3395** [comment] 2021-04-17 14:29
> I love this idea. If you recall the exact file you found it in and can leave that noted here that would be helpful so we can see what all this change would require.
> 
> Update:It looks like the cause of this is in this location:
> https://github.com/usmannasir/cyberpanel/blob/stable/install/install.py#L2322-L2350

Not sure why we need to make the Rainloop admin password unique from the cp password.

The real admin password is located here: with hash:
/usr/local/lscp/cyberpanel/rainloop/data/_data_/_default_/configs/application.ini

; Login and password for web admin panel
admin_login = "admin"
admin_password = "Password"

**Comment by meramsey** [comment] 2021-04-18 05:48
So there wasn't a way to pass the same pass to the process that changes the rainloop installer easily so I did the next best thing which was ensuring that it shows the password upon install and links to the admin page as well as adding the OLS/LS admin link in the postinstall. This should hopefully make this less of an issue going forward.

Fix is in v2.1.1-dev if you want to give it a try on a fresh install and let us know.
https://github.com/usmannasir/cyberpanel/commit/a48c89f163705ced9cb2e2795582d47ee7b48144

**Comment by meramsey** [comment] 2021-04-21 22:39
So i just tested this out and looks to work perfectly and shows the rainloop admin password upon fresh install and it is in stable 2.1.1 now as well.  I know it is not the same but it is displayed now so you can see it immediately like the others and login and change it to your desired password as applicable.

![image](https://user-images.githubusercontent.com/1596188/115629654-c7910780-a2d0-11eb-8004-70bdbe3f73a9.png)

**Closed as completed by meramsey** 2021-04-21 22:39 UTC
